// Std
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

constexpr const char NewLine = '\n';
constexpr const char *Indent = "    ";
constexpr uint32_t BytesPerLine = 32;

struct GenerateFileOptions
{
    std::string InputFilePath;
    std::string OutputFilePath;
};

int GenerateFile(const GenerateFileOptions &options);

int main(int argc, char **argv)
{
    if (argc < 3)
    {
        std::cout << "Usage:" << NewLine;
        std::cout << "bin2code <input-file> <output-file>" << NewLine;
        return EXIT_FAILURE;
    }

    GenerateFileOptions options {
        .InputFilePath = argv[1],
        .OutputFilePath = argv[2],
    };

    return GenerateFile(options);
}

int GenerateFile(const GenerateFileOptions &options)
{
    std::ifstream inputFile(options.InputFilePath, std::ios::binary | std::ios::ate);
    std::ofstream outputFile(options.OutputFilePath, std::ios::binary | std::ios::trunc);

    if (!inputFile.is_open())
    {
        std::cout << "Failed to open input file: " << options.InputFilePath << NewLine;
        return EXIT_FAILURE;
    }

    if (!outputFile.is_open())
    {
        std::cout << "Failed to open output file: " << options.OutputFilePath << NewLine;
        return EXIT_FAILURE;
    }

    const auto fileSize = inputFile.tellg();
    const auto fileSizeInBytes = static_cast<uint64_t>(fileSize);

    inputFile.seekg(0);

    outputFile << "// ************************************" << NewLine;
    outputFile << "// This file was generated by bin2code." << NewLine;
    outputFile << "// ************************************" << NewLine;
    outputFile << "#pragma once" << NewLine;
    outputFile << NewLine;
    outputFile << "#include <array>" << NewLine;
    outputFile << "#include <cstdint>" << NewLine;
    outputFile << NewLine;

    const auto inputFileSystemPathFilename = std::filesystem::path(options.InputFilePath).filename().string();
    const auto outputVariableName = inputFileSystemPathFilename.substr(0, inputFileSystemPathFilename.find_first_of('.'));

    outputFile << "// Binary content of " << inputFileSystemPathFilename << NewLine;

    outputFile << "constexpr std::array<const uint8_t, " << fileSizeInBytes << "> " << outputVariableName << NewLine;
    outputFile << "{";

    uint64_t index = 0;
    while (true)
    {
        const auto byte = inputFile.get();
        if (inputFile.eof()) break;

        if ((index++ % BytesPerLine) == 0)
        {
            outputFile << NewLine
                       << Indent;
        }

        outputFile << "0x" << std::hex << std::setfill('0') << std::setw(2) << static_cast<uint32_t>(byte) << ((index % BytesPerLine) == 0 ? "," : ", ");
    }

    outputFile << NewLine
               << "};" << NewLine;

    return EXIT_SUCCESS;
}
